#!/usr/bin/env python3
"""Score the cross-browser captures and write the capability matrix.

    python tools/matrix/analyze.py

Reads .cache/matrix/<engine>-<width>-<scheme>/ written by capture.mjs and
applies exactly the checks tools/techniques/verify.py uses in Chrome — frame
differencing for animation, pixel reads for the boundary tests — so every
engine is judged by the same code. Writes docs/matrix/matrix.json,
docs/CAPABILITY-MATRIX.md and evidence crops in docs/matrix/rendered/.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "tools" / "techniques"))
from verify import STATIC_BY_DESIGN, boundary, changed_fraction  # noqa: E402

CAPTURES = ROOT / ".cache" / "matrix"
OUT = ROOT / "docs" / "matrix"
ENGINES = ["chromium", "firefox", "webkit"]
LABEL = {"chromium": "Chromium", "firefox": "Firefox", "webkit": "WebKit (Safari's engine)"}
PASSES = [(1280, "dark"), (1280, "light"), (390, "dark"), (390, "light")]
FRAMES = 8
EVIDENCE = {"test-script.svg", "test-external-image.svg", "test-external-font.svg",
            "test-foreign-object.svg", "theme-aware.svg"}


def score(engine: str, width: int, scheme: str) -> dict:
    d = CAPTURES / f"{engine}-{width}-{scheme}"
    lf = d / "listing.json"
    if not lf.exists():
        return {"missing": True}
    listing = json.loads(lf.read_text(encoding="utf-8"))
    if "error" in listing:
        return {"error": listing["error"]}
    out = {"version": None, "container": listing.get("container"), "images": {}}
    for im in listing["images"]:
        f = im.get("file")
        if not f:
            continue
        row = {"loaded": im["loaded"], "shown": im["shown"], "rendered_w": round(im["w"], 1)}
        frames = [d / f"{f}.{i}.png" for i in range(FRAMES)]
        if im["shown"] and all(p.exists() for p in frames):
            imgs = [Image.open(p).convert("RGB") for p in frames]
            row["changed"] = round(max(changed_fraction(imgs[0], x) for x in imgs[1:]), 4)
            row["animates"] = row["changed"] > 0.003
            row.update({k: (list(v) if isinstance(v, tuple) else v) for k, v in boundary(f, imgs[0]).items()})
            if f in EVIDENCE and scheme == "dark" and width == 1280:
                (OUT / "rendered").mkdir(parents=True, exist_ok=True)
                imgs[0].save(OUT / "rendered" / f"{engine}-{Path(f).stem}.png", optimize=True)
        out["images"][f] = row
    return out


def main() -> None:
    results = {e: {f"{w}-{s}": score(e, w, s) for w, s in PASSES} for e in ENGINES}
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "matrix.json").write_text(json.dumps(results, indent=1), encoding="utf-8")
    write_markdown(results)
    for e in ENGINES:
        ok = sum(1 for p in results[e].values() if "images" in p)
        print(f"{e}: {ok}/4 passes scored")


def cell_anim(results: dict, engine: str, file: str) -> str:
    rows = [results[engine].get(f"{w}-{s}", {}).get("images", {}).get(file) for w, s in PASSES]
    rows = [r for r in rows if r]
    if not rows:
        return "not captured"
    if not all(r["loaded"] for r in rows if r["shown"]):
        return "✗ fails to load"
    if file in STATIC_BY_DESIGN:
        return "✓"
    return "✓ animates" if any(r.get("animates") for r in rows) else "✓ **no motion**"


def uniform(results: dict, engine: str, file: str, key: str):
    vals = set()
    for w, s in PASSES:
        r = results[engine].get(f"{w}-{s}", {}).get("images", {}).get(file)
        if r and r.get("shown") and key in r:
            vals.add(json.dumps(r[key]))
    if not vals:
        return None
    return json.loads(vals.pop()) if len(vals) == 1 else "inconsistent"


def theme_shown(results: dict, engine: str, prefix: str, scheme: str) -> str:
    imgs = results[engine].get(f"1280-{scheme}", {}).get("images", {})
    vis = [f[len(prefix):-4] for f, r in imgs.items() if f.startswith(prefix) and r["shown"]]
    return ", ".join(vis) or "nothing"


def write_markdown(results: dict) -> None:
    files = sorted({f for e in ENGINES for p in results[e].values() for f in p.get("images", {})})
    techniques = [f for f in files if not f.startswith(("test-", "theme-"))]
    head = "| | " + " | ".join(LABEL[e] for e in ENGINES) + " |"
    sep = "|---|" + "---|" * len(ENGINES)
    L = [
        "# Capability matrix",
        "",
        "What works where, tested rather than assumed. Generated by `tools/matrix/analyze.py` "
        "from captures made by `tools/matrix/capture.mjs` — do not edit by hand.",
        "",
        "Every cell was checked by loading `docs/techniques/GALLERY.md` inside GitHub's rendered page "
        "in each engine, at 1280px and 390px, in dark and light schemes, and scoring it with the same "
        "code used for the Chrome verification: eight frames 0.8s apart for animation, pixel reads for "
        "the boundary tests. WebKit is Safari's rendering engine; it is not iOS Safari or the GitHub "
        "mobile app, which are covered by the manual checks at the end.",
        "",
        "## Techniques",
        "",
        head, sep,
    ]
    for f in techniques:
        L.append(f"| [`{f}`](techniques/examples/{f}) | " +
                 " | ".join(cell_anim(results, e, f) for e in ENGINES) + " |")

    L += ["", "## Theme switching (dark scheme → light scheme)", "", head, sep]
    for prefix, name in (("theme-picture-", "`<picture>` + `prefers-color-scheme`"),
                         ("theme-fragment-", "`#gh-dark-mode-only` / `#gh-light-mode-only`")):
        L.append(f"| {name} | " + " | ".join(
            f"{theme_shown(results, e, prefix, 'dark')} → {theme_shown(results, e, prefix, 'light')}"
            for e in ENGINES) + " |")
    L.append("| `@media` inside the SVG | " + " | ".join(
        f"{results[e].get('1280-dark', {}).get('images', {}).get('theme-aware.svg', {}).get('in_svg_scheme', '?')} → "
        f"{results[e].get('1280-light', {}).get('images', {}).get('theme-aware.svg', {}).get('in_svg_scheme', '?')}"
        for e in ENGINES) + " |")

    L += ["", "## Boundary tests", "", head, sep]
    def fmt(v, yes, no):
        return "—" if v is None else ("inconsistent" if v == "inconsistent" else (yes if v else no))
    L.append("| `<script>` inside the SVG | " + " | ".join(
        fmt(uniform(results, e, "test-script.svg", "script_ran"), "**runs**", "blocked") for e in ENGINES) + " |")
    L.append("| External `<image>` | " + " | ".join(
        str(uniform(results, e, "test-external-image.svg", "external_image") or "—") for e in ENGINES) + " |")
    L.append("| `@import` web font | " + " | ".join(
        fmt(uniform(results, e, "test-external-font.svg", "web_font_loaded"), "**loads**", "blocked") for e in ENGINES) + " |")
    L.append("| HTML in `<foreignObject>` | " + " | ".join(
        fmt(uniform(results, e, "test-foreign-object.svg", "foreign_object_rendered"), "renders", "**not rendered**")
        for e in ENGINES) + " |")

    cache_path = ROOT / "docs" / "matrix" / "cache.json"
    if cache_path.exists():
        c = json.loads(cache_path.read_text(encoding="utf-8"))
        L += ["", "## How long an update takes to show", "",
              "Measured by `tools/matrix/cache_probe.py`: push a new version of a committed SVG, then poll "
              "until it's served. A profile README embeds images by branch path, so the branch URL is what "
              "visitors see.", "",
              "| Round | Branch URL (what a README uses) | Commit-pinned URL | Cache header |", "|---|---|---|---|"]
        for i, r in enumerate(c["rounds"], 1):
            L.append(f"| {i} | {r['branch_url_seconds']}s | {r['pinned_url_seconds']}s | `{r['warm_cache_control']}` |")
        L += ["", f"Polled every {c['poll_every_seconds']}s from one location on {c['measured_at'][:10]}. "
              "A pushed change takes about five minutes to appear — the CDN's `max-age=300` — while a URL "
              "pinned to the commit is fresh within seconds but has to be rewritten into the README on every "
              "update."]
    L += [
        "",
        "## Phone layout",
        "",
        "The phone column measured 309px on a real profile page (Chromium, true mobile emulation — "
        "see `docs/survey/FINDINGS.md`). Firefox has no mobile emulation mode, so its 390px pass is a "
        "narrow desktop viewport.",
        "",
        "## Not testable here — check by hand",
        "",
        "iOS Safari and the GitHub mobile apps can't be driven from this machine. The gallery is "
        "built so each answer is visible by eye; open it on the device and read it off:",
        "",
        "<https://github.com/hammadshakeelai/github-profile-blueprint/blob/v2/research/docs/techniques/GALLERY.md>",
        "",
        "| Check | What you should see if it works |",
        "|---|---|",
        "| Animation | The dot moves along its curve; the ring spins; stars twinkle |",
        "| `<picture>` theming | Switch the device between dark and light: the card label changes between \"DARK variant\" and \"LIGHT variant\" |",
        "| In-SVG theming | \"Theme-aware SVG\" card background follows the device theme |",
        "| Script test | Panel is **green** (red would mean scripts ran) |",
        "| External image | A \"?\" or a broken-image icon, not a photo |",
        "| `<foreignObject>` | A purple \"HTML\" pill next to \"inside SVG\"; a blank card means unsupported |",
        "| `<details>` | The collapsed block at the bottom expands on tap |",
        "",
        "Record results in this table when checked; until then these cells are **unverified**.",
    ]
    (ROOT / "docs" / "CAPABILITY-MATRIX.md").write_text("\n".join(L) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
