#!/usr/bin/env python3
"""Health check for profile-README generator and tool repositories.

    python tools/survey/tools_health.py

Seeds from the '## Tools' section of abhisheknaiidu/awesome-github-profile-readme
plus the major generators seen in the survey, then records each repository's
stars, last push and archived flag. Writes docs/survey/TOOLS.md and
docs/survey/data/tools.json.

Complements GENERATORS.md: that table measures services *in use* by whether
their images load; this one measures the projects behind them by whether
anyone still maintains them.
"""
from __future__ import annotations

import concurrent.futures as cf
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import harvest  # noqa: E402  (reuses the cached, token-scoped HTTP client)

ROOT = Path(__file__).resolve().parents[2]
SURVEY = ROOT / "docs" / "survey"

# Major generators observed in the survey, or their successors, that the
# awesome list's Tools section doesn't link directly.
SEED = [
    "anuraghazra/github-readme-stats", "stats-organization/github-stats-extended",
    "stats-organization/github-readme-stats-action", "DenverCoder1/github-readme-streak-stats",
    "DenverCoder1/readme-typing-svg", "DenverCoder1/custom-icon-badges", "ryo-ma/github-profile-trophy",
    "Ashutosh00710/github-readme-activity-graph", "vn7n24fzkq/github-profile-summary-cards",
    "lowlighter/metrics", "Platane/snk", "kyechan99/capsule-render", "tandpfun/skill-icons",
    "antonkomarev/github-profile-views-counter", "journey-ad/Moe-Counter", "novatorem/novatorem",
    "kittinan/spotify-github-profile", "athul/waka-readme", "anmol098/waka-readme-stats",
    "gautamkrishnar/blog-post-workflow", "jamesgeorge007/github-activity-readme",
    "badges/shields", "simple-icons/simple-icons", "devicons/devicon", "yoshi389111/github-profile-3d-contrib",
    "rahuldkjain/github-profile-readme-generator", "abhisheknaiidu/awesome-github-profile-readme",
]


def tools_section_repos() -> list[str]:
    r = harvest.http_get(f"{harvest.API}/repos/abhisheknaiidu/awesome-github-profile-readme/readme",
                         accept="application/vnd.github.raw")
    md = r["body"].decode("utf-8", "replace")
    m = re.search(r"^## Tools\s*$(.*?)^## ", md, re.S | re.M)
    block = m.group(1) if m else ""
    repos = re.findall(r"https?://github\.com/([A-Za-z0-9-]+/[A-Za-z0-9._-]+)", block)
    repos = [re.sub(r"(\.git|#.*)$", "", x) for x in repos]
    # Marketplace and topic links look like owner/repo but are GitHub pages.
    return [x for x in repos if x.split("/")[0].lower() not in harvest.RESERVED]


def health(full: str) -> dict:
    r = harvest.http_get(f"{harvest.API}/repos/{full}", accept="application/vnd.github+json")
    if r["status"] != 200:
        return {"repo": full, "status": f"http-{r['status']}"}
    d = json.loads(r["body"])
    pushed = d.get("pushed_at")
    months = None
    if pushed:
        months = round((datetime.now(timezone.utc) -
                        datetime.fromisoformat(pushed.replace("Z", "+00:00"))).days / 30.44, 1)
    return {"repo": d.get("full_name", full), "status": "ok", "stars": d.get("stargazers_count", 0),
            "pushed_at": pushed, "months_since_push": months, "archived": d.get("archived", False),
            "description": (d.get("description") or "").strip()[:140]}


def verdict(h: dict) -> str:
    if h["status"] != "ok":
        return "gone"
    if h["archived"]:
        return "archived"
    m = h["months_since_push"] or 0
    return "active" if m <= 6 else "slowing" if m <= 24 else "dormant"


def main() -> None:
    harvest.TOKEN = harvest.gh_token()
    repos = list(dict.fromkeys(SEED + tools_section_repos()))
    with cf.ThreadPoolExecutor(8) as ex:
        rows = list(ex.map(health, repos))
    for h in rows:
        h["verdict"] = verdict(h)
    rows.sort(key=lambda h: (-(h.get("stars") or 0), h["repo"].lower()))
    (SURVEY / "data" / "tools.json").write_text(json.dumps(rows, indent=1), encoding="utf-8")

    counts = {v: sum(h["verdict"] == v for h in rows) for v in ("active", "slowing", "dormant", "archived", "gone")}
    lines = [
        "# Tools",
        "",
        "Generator and tool repositories behind profile READMEs, with maintenance status. "
        "Generated by `tools/survey/tools_health.py` — do not edit by hand.",
        "",
        f"{len(rows)} repositories: " + ", ".join(f"{n} {v}" for v, n in counts.items() if n) + ".",
        "",
        "**active** pushed within 6 months · **slowing** within 2 years · **dormant** older · "
        "**archived** read-only · **gone** missing or renamed.",
        "",
        "Pushes include bot and dependency-update commits, so *active* means the repository is "
        "touched, not necessarily that a human is developing it.",
        "",
        "| Repository | Stars | Last push | Status | What it is |",
        "|---|--:|---|---|---|",
    ]
    for h in rows:
        if h["status"] != "ok":
            lines.append(f"| {h['repo']} | | | gone | |")
            continue
        desc = h["description"].replace("|", "\\|")
        lines.append(f"| [{h['repo']}](https://github.com/{h['repo']}) | {h['stars']:,} | "
                     f"{(h['pushed_at'] or '')[:10]} | {h['verdict']} | {desc} |")
    (SURVEY / "TOOLS.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"{len(rows)} repos: {counts}")


if __name__ == "__main__":
    main()
